export const auditEntityTypeValues = [
    "trooper",
    "trooper_rank",
    "trooper_qualification",
    "trooper_bio",
    "attendance",
    "trooper_attendance",
    "training_completion",
    "billet_assignment",
    "department_assignment",
    "campaign",
    "event",
    "operation",
    "announcement",
    "event_series",
    "rank",
    "department",
    "department_position",
    "unit_element",
    "billet",
    "medal",
    "trooper_medal",
    "wiki_collection",
    "wiki_page",
] as const;
