export const ranks: { [key: number]: { name: string; abbreviation: string } } =
  {
    1: { name: "Clone Commander", abbreviation: "CC" },
    2: { name: "Clone Captain", abbreviation: "CC" },
    3: { name: "Chief Warrant Officer", abbreviation: "CWO" },
    4: { name: "Clone First Lieutenant", abbreviation: "CC" },
    5: { name: "Clone Second Lieutenant", abbreviation: "CL" },
    6: { name: "Clone Squadron Commander", abbreviation: "CXO" },
    7: { name: "Clone Warrant Officer Grade 5", abbreviation: "CW" },
    8: { name: "Clone Sergeant", abbreviation: "CS" },
    9: { name: "Clone Flight Officer", abbreviation: "CXS" },
    10: { name: "Clone Warrant Officer Grade 4", abbreviation: "CW" },
    11: { name: "Clone Corporal", abbreviation: "CP" },
    12: { name: "Jr Clone Flight Officer", abbreviation: "CXP" },
    13: { name: "Clone Warrant Officer Grade 3", abbreviation: "CW" },
    14: { name: "Clone Lance Corporal", abbreviation: "CLC" },
    15: { name: "Clone Warrant Officer Grade 2", abbreviation: "CW" },
    16: { name: "Clone Specialist", abbreviation: "CSP" },
    17: { name: "Clone Ensign", abbreviation: "CXX" },
    18: { name: "Clone Warrant Officer Grade 1", abbreviation: "CW" },
    19: { name: "Veteran Clone Trooper", abbreviation: "VCT" },
    20: { name: "Clone Aviator", abbreviation: "CX" },
    21: { name: "Senior Clone Trooper", abbreviation: "SCT" },
    22: { name: "Clone Aviator Cadet", abbreviation: "CXC" },
    23: { name: "Clone Trooper", abbreviation: "CT" },
    24: { name: "Clone Recruit", abbreviation: "CR" },
  };
