INSERT INTO qualifications (id, name, abbreviation) VALUES
    (1, 'Basic Training', 'BT'),
    (2, 'Auto-Rifleman', 'AR'),
    (3, 'Anti-Tank', 'AT'),
    (4, 'Marksman', 'MRK'),
    (5, 'Combat Life Saver', 'CLS'),
    (6, 'Close Quarters Combatant', 'CQC'),
    (7, 'Grenadier', 'GRN'),
    (8, 'Airborne', 'ABR'),
    (9, 'Demolition Specialist', 'DEMO'),
    (10, 'Medic', 'MED'),
    (11, 'Basic Leadership Course', 'BLC'),
    (12, 'Advance Leadership Course', 'ALC'),
    (13, 'Command Leadership Course', 'CLC'),
    (14, 'Detachment Leadership Course', 'DLC'),
    (15, 'Rotary Wing', 'RTW'),
    (16, 'Fixed Wing', 'FXW'),
    (17, 'Advance Recon Commandos', 'ARC'),
    (18, 'Advance Recon Force', 'ARF'),
    (19, 'Republic Commando', 'RCM'),
    (20, 'Joint Attack Controller', 'RTO');